name       : haskell-silently
version    : 1.2.5.1
release    : 4
source     :
    - https://hackage.haskell.org/package/silently-1.2.5.1/silently-1.2.5.1.tar.gz : 7fc9baf6f47ffc082e7e05c9dade1451bdee06a0c4e2d882e8e0b692f50bfad1
license    : BSD-3-Clause
component  : programming.haskell
summary    : Prevent or capture writing to stdout and other handles.
description: |
    Prevent or capture writing to stdout and other handles.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
