name       : haskell-silently
version    : 1.2.5
release    : 1
source     :
    - http://hackage.haskell.org/package/silently-1.2.5/silently-1.2.5.tar.gz : cef625635053a46032ca53b43d311921875a437910b6568ded17027fdca83839
license    : BSD-3-Clause
component  : programming.haskell
summary    : Prevent or capture writing to stdout and other handles. 
description: |
    Prevent or capture writing to stdout and other handles. 
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
